Transform: AWS::Serverless-2016-10-31
Description: Stack for present error handling in Lambda functions
Resources:
  SuccessLambda:

    Type: AWS::Serverless::Function
    Properties:
      Handler: AwsLambdaErrorHandling.Functions::AwsLambdaErrorHandling.Functions.SuccessLambda::Invoke

  FailLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: AwsLambdaErrorHandling.Functions::AwsLambdaErrorHandling.Functions.FailLambda::Invoke

Globals:
  Function:
    Runtime: dotnetcore3.1
    CodeUri: bin/Release/netcoreapp3.1/publish
    MemorySize: 512
    Timeout: 10